# Generated by Django 2.0.7 on 2018-07-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brewery', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=80)),
                ('price', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BeerStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brewery', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=80)),
                ('price', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField()),
                ('street_number', models.CharField(blank=True, max_length=80)),
                ('street_name', models.CharField(blank=True, max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=80)),
                ('prov_state', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, max_length=80)),
            ],
        ),
    ]
